name: kube_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  kubernetes: ^0.1.3
  dartz: ^0.10.1
  equatable: ^2.0.3
  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.8
  path_provider: ^2.0.11
  path: ^1.8.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  drift_dev: ^1.7.0
  build_runner: ^2.1.11

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
